---
resources:
- name: build-gdpr
  type: git
  source:
    uri: https://github.com/alphagov/zendesk-scripts.git
    branch: master

- name: gdpr-tickets-repository
  type: docker-image
  source:
    repository: "((readonly_private_ecr_repo_url))"
    tag: concourse-gdpr-tickets-latest

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: build-gdpr
    trigger: true
  - put: gdpr-tickets-repository
    params:
      build: build-gdpr