resources:
- name: zendesk-scripts
  type: git
  icon: github-circle
  source:
    branch: master
    uri: "https://github.com/alphagov/zendesk-scripts.git"

- name: nightly
  type: time
  icon: alarm
  source:
    location: Europe/London
    start: "01:00 AM"
    stop: "05:00 PM"

- name: gdpr-repository
  type: docker-image
  source:
    repository: "((readonly_private_ecr_repo_url))"
    tag: concourse-gdpr-tickets-latest

jobs:
- name: build-zendesk-GDPR-cleaner
  serial: true
  plan:
  - get: zendesk-scripts
    trigger: true
  - put: gdpr-repository
    params:
      build: zendesk-scripts

- name: delete-tickets-and-user-accounts
  serial: true
  plan:
  - get: nightly
    trigger: true
  - get: gdpr-repository
    trigger: true
    passed: [build-zendesk-GDPR-cleaner]
  - task: run
    image: gdpr-repository
    config:
      platform: linux
      run:
        args:
        - -xce
        - |
          cd /usr/src/app
          export ZENDESK_LOG_FILE=zendesk-GDPR-tickets.`date +%Y-%m-%d`
          bundle exec ruby /usr/src/app/lib/tickets-autom8-able.rb
          aws s3 cp $ZENDESK_LOG_FILE s3://${S3_BUCKET_NAME}/
          export ZENDESK_LOG_FILE=zendesk-GDPR-users.`date +%Y-%m-%d`
          bundle exec ruby /usr/src/app/lib/user-ids-autom8-able.rb
          aws s3 cp $ZENDESK_LOG_FILE s3://${S3_BUCKET_NAME}/
        path: /bin/bash
      params:
        S3_BUCKET_NAME: ((readonly_private_bucket_name))
        ZENDESK_URL: ((zendesk-url))
        ZENDESK_USER_EMAIL: ((zendesk-email))
        ZENDESK_TOKEN: ((zendesk-token))

  - task: cronitor-zendesk-GDPR-cleaner
    timeout: 1m
    config:
      platform: linux
      params:
        CRONITOR_LINK: https://cronitor.link/FempMQ/complete
      image_resource:
          type: docker-image
          source:
            repository: governmentpaas/curl-ssl
            tag: cd404e5f6e7b96082c586e80921189769131f593
      run:
        path: sh
        args:
          - -c
          - |
            set -ue
            echo 'Curling cronitor'
            curl --fail "$CRONITOR_LINK"
            echo 'Curled cronitor successfully'
